Repository HCMUS-ROBOTICS/ssdf-sim-adapter, pull requests merged in 2021-09, with the labels that each got.

#15 Signal ROS to exit
  src/sim_adapter/uit_adapter.py
Labels: bug

#18 Add verify command for /cmd_vel topic to README
  README.md
Labels: documentation

#16 Add launch files for simulators
  README.md
  bin/node.py
  launch/dira.launch
  launch/uit.launch
  requirements.txt
Labels: enhancement

#20 Switch from eventlet to tornado
  CMakeLists.txt
  README.md
  bin/node.py
  launch/uit.launch
  src/sim_adapter/simulator.py
  src/sim_adapter/uit_adapter.py
Labels: bug, enhancement

#26 update image format
  src/sim_adapter/dira_adapter.py
  src/sim_adapter/simulator.py
  src/sim_adapter/uit_adapter.py
Labels: bug, documentation
